### PR TITLE
Added ensurable to f5_command, f5_sslkey, and f5_sslcertificate.

### PR DESCRIPTION
**Pull request by bFekete**
Added debug statements. Added self.instances, self.prefetch and destroy functions. Unused function create_message.

Closes issue #20 #21

### CODE REVIEW

**Comment by bFekete** [comment]
@abrader Could you review this PR when you get a chance? This change allows f5_sslcertificate, f5_sslkey, and f5_command to work. I changed the properties to parameters since we're just importing the ssl cert and key. We aren't really managing any configuration just the existence.

**Comment by abrader** [comment]
@bFekete thank you for bringing this to my attention.  Have you tested this code to date? Code looks clean to me except for the f5_command ensurable bit.  Can you explain @bFekete why this is necessary?  The presence of running a TMSH command seems redundant.  @ericzji once we determine what commits are ready for merge, can you confirm you will be able to test this PR?  This is very much needed to getting puppet resource working, for the cert types at least.

**Comment by bFekete** [comment]
@abrader I've tested this code multiple times with different test cases. The F5_command resource was not working at all since it wasn't ensurable. It would never send a POST request. I'm not a big fan of the F5_command because its not idempotent but I figured I'll at least get it into a usable state.

**Comment by bFekete** [comment]
@ericzji Can you review and merge?

**Pull request merged**
