### PR TITLE
WIP: Added ensurable so it calls API POST

### LINKED ISSUE #20: Trouble with f5_sslcertificate and f5_sslkey
# As-is no action taken on the F5
If I use the types as documented, I get "defined" message but no action is taken on the F5:

This Puppet code:

```puppet
f5_sslkey{'/var/tmp/testing.example.com.crt':
    keyname         => 'testingexamplecom_crt',
    from_local_file => '/var/tmp/testing.example.com.crt',
}
f5_sslcertificate{'/var/tmp/testing.example.com.key':
    certificate_name => 'testingexamplecom_key',
    from_local_file  => '/var/tmp/testing.example.com.key',
}
```

Leads to this output:

```puppet
Notice: /Stage[main]/Profiles::F5test/F5_sslkey[/var/tmp/testing.example.com.crt]/keyname: defined 'keyname' as 'testingexamplecom_crt'
Notice: /Stage[main]/Profiles::F5test/F5_sslkey[/var/tmp/testing.example.com.crt]/from_local_file: defined 'from_local_file' as '/var/tmp/testing.example.com.crt'
Notice: /Stage[main]/Profiles::F5test/F5_sslcertificate[/var/tmp/testing.example.com.key]/certificate_name: defined 'certificate_name' as 'testingexamplecom_key'
Notice: /Stage[main]/Profiles::F5test/F5_sslcertificate[/var/tmp/testing.example.com.key]/from_local_file: defined 'from_local_file' as '/var/tmp/testing.example.com.key'
```

# Adding "ensurable" leads to an error about the key/cert format

If I add "ensurable" to the types right below the "apply_to_device" line, then the provider does talk to the F5 but gets an error about the key format. Almost every other type has "ensurable". Here's the error:

```puppet
Error: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: Certificate/Key has unknown format or security type (/Common/testingexamplecom_crt.key).","errorStack":[],"apiError":3} at /etc/puppetlabs/code/environments/production/sssmodules/profiles/manifests/f5test.pp:17
Error: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: Certificate/Key has unknown format or security type (/Common/testingexamplecom_crt.key).","errorStack":[],"apiError":3} at /etc/puppetlabs/code/environments/production/sssmodules/profiles/manifests/f5test.pp:17
Wrapped exception:
REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: Certificate/Key has unknown format or security type (/Common/testingexamplecom_crt.key).","errorStack":[],"apiError":3}
Error: /Stage[main]/Profiles::F5test/F5_sslkey[/var/tmp/testing.example.com.crt]/ensure: change from absent to present failed: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: Certificate/Key has unknown format or security type (/Common/testingexamplecom_crt.key).","errorStack":[],"apiError":3} at /etc/puppetlabs/code/environments/production/sssmodules/profiles/manifests/f5test.pp:17
Error: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: unable to validate certificate, invalid x509 file (/Common/testingexamplecom_key.crt).","errorStack":[],"apiError":3} at /etc/puppetlabs/code/environments/production/sssmodules/profiles/manifests/f5test.pp:21
Error: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: unable to validate certificate, invalid x509 file (/Common/testingexamplecom_key.crt).","errorStack":[],"apiError":3} at /etc/puppetlabs/code/environments/production/sssmodules/profiles/manifests/f5test.pp:21
Wrapped exception:
REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: unable to validate certificate, invalid x509 file (/Common/testingexamplecom_key.crt).","errorStack":[],"apiError":3}
Error: /Stage[main]/Profiles::F5test/F5_sslcertificate[/var/tmp/testing.example.com.key]/ensure: change from absent to present failed: Could not set 'present' on ensure: REST failure: HTTP status code 400 detected.  Body of failure is: {"code":400,"message":"01070712:3: unable to validate certificate, invalid x509 file (/Common/testingexamplecom_key.crt).","errorStack":[],"apiError":3} at /etc/puppetlabs/code/environments/production/sssmodules/profiles/manifests/f5test.pp:21
```

# But Curl works
If I use curl to do the same job it works fine:

```bash
curl -sk -u admin:admin -H "Content-Type: application/json" -X POST https://f5-sandbox.bor.usg.edu/mgmt/tm/sys/crypto/cert -d '{"command":"install","name":"test","from-local-file":"/var/tmp/testing.example.com.crt"}'
```

Output:

```json
{"kind":"tm:sys:crypto:cert:installstate","command":"install","name":"test","from-local-file":"/var/tmp/testing.example.com.crt"}
```

And `tmsh list sys file ssl-cert all` on the F5 shows the cert.

# I failed to convince Faraday to log :)
I tried and failed to get Faraday to log the HTTP headers and the body of the POST. Surely there's just a subtle difference between what Puppet and Curl are doing. But I can't spot it!

Thanks for any help!

### PR DESCRIPTION
**Pull request by bFekete**
Fixes #20 and #21. They are not idempotent but this will at least allow them to be used.

### CODE REVIEW

**Comment by bFekete** [comment]
@alexjfisher If you don't mind, could you review this when have a chance?

**Comment by alexjfisher** [comment]
`ensurable` is really for types whose resources can be created *and* destroyed.  It's perfect for things like pools, virtual servers etc.

It's been used in a lot of other places in this module it really shouldn't have.  When a type is made `ensurable`, it must implement `create`, `exists?` and `destroy`.
https://github.com/f5devcentral/f5-puppet/blob/master/lib/puppet/provider/f5_sslkey/rest.rb#L28 makes `exists?` always return false.  In this way `create` is always called.  This is an abuse of the puppet API IMO.

It's really crazy that eg f5_command would call create and execute a post on each puppet run.  Worse still, AFAICT, lots of types do this and don't even report back to puppet that the resource has been modified.  It's not great when puppet is making changes silently...

When this module was open-sourced, I was excited about the possibilities and really hoping to make it the new way we manage F5 devices where I am.   Unfortunately, with all the problems it has, I've not been able to convince anyone else (or myself) this would be a good idea, (and the person more directly responsible for our F5s prefers ansible)!  It's a real shame.  I was hoping for better and was prepared to to help with its development.  Maybe in the future...

**Comment by happymcplaksin** [comment]
@alexjfisher What do you recommend instead of `ensurable` in cases like `f5_command`?

Maybe not for f5_command but the ssl cert types *could* implement everything `ensurable` requires. So adding `ensurable` to those seems like at least a good baby step :)

I too hoped more worked out of the box with this module but it still seems promising.

**Comment by bFekete** [comment]
A demo was planned and I had to get those 3 resource types to at least create to show the F5 and Puppet use case. I know it's not the ideal solution but just a bandage.

@alexjfisher I completely agree. Every resource should be idempotent along with being able to manage configuration and not just creation. I plan on contributing more once I get the hang of puppet devices. Resource types, Puppet, and REST APIs aren't new to me but puppet device and the F5 are.

If we can compile a list of what needs to be improved, I'm sure I can contribute.

**Comment by bFekete** [comment]
I'm currently testing the F5_sslcertificate and F5_sslkey with proper destroy and exists? functions. For F5_command that's a bit tricky. 

Ensurable was taken out with this commit: https://github.com/f5devcentral/f5-puppet/commit/a0b5db64da920f48559ca5dd74b61aa8183d4630

**Comment by bFekete** [comment]
Opened a new PR #26

**Pull request closed without merging**
