### PR TITLE
Make ftp work again

### PR DESCRIPTION
**Pull request by ryanbsaunders**
Fix some copy-pasta and remove trailing space to make the FTP profile work.

Part of this duplicates the fix in https://github.com/f5devcentral/f5-puppet/pull/33 made by @mcmartins.

### CODE REVIEW

**Comment by drewby08** [comment]
👍

**Comment by derbious** [comment]
👍

**Comment by scshitole** [comment]
F5 is in progress of assigning resource for this PR.

**Comment by mcmartins** [comment]
Did anyone test this PR? I can see it was merged and is available in v1.9.0 but I'm still having the same problem as before on every puppet run:

```
Resource                              | Event             | Changed from | Changed to
File: ...network/f5/virtualservers.pp | Corrective change | none         | /Common/ftp
```

I've reverted my Puppet file to use my fork again...

**Comment by ryanbsaunders** [comment]
@mcmartins I tested over the weekend and didn't have this issue.  Going to run against another device that has the FTP profile set and ensure that it's still working.

**Pull request merged**
